services:
  postgres:
    image: postgres:latest
    container_name: postgres_work05
    environment:
      POSTGRES_USER: user_tw05
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db_tw05
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
    working_dir: /code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGO=${JWT_ALGO}
      - ACCESS_EXPIRES_MINUTES=${ACCESS_EXPIRES_MINUTES}
      - REFRESH_EXPIRES_DAYS=${REFRESH_EXPIRES_DAYS}
      - PYTHONPATH=/code

volumes:
  postgres_data: